language: php
notifications:
  email: false
php:
- 5.5
env:
  global:
before_install:
  - set -ex
  - export WP_CORE_DIR="/tmp/wordpress"
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot
before_script:
  # apache
  - sudo apt-get update -qq
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-curl php5-mysql php5-intl > /dev/null
  # wordpress
  - mkdir $WP_CORE_DIR  
  - cd $WP_CORE_DIR
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar  
  - php wp-cli.phar core download 
  - php wp-cli.phar core config --dbname=wordpress_test --dbuser=root
  - php wp-cli.phar core install --url=http://localhost --title="WP" --admin_user=admin --admin_email=test@example.org --admin_password=test
  - php wp-cli.phar plugin install easy-grabber
  - php wp-cli.phar --info
  # tests
script:
  - cd $TRAVIS_BUILD_DIR
  - "wget http://codeception.com/codecept.phar"
  - php ./codecept.phar run acceptance --steps
after_script: